Repository greymatter-io/helm-charts, pull requests merged in 2019-11, with the labels that each got.

#373 Update greymatter.yaml with new mongo values
  greymatter.yaml
Labels: size/XS

#375 update dashboard and slo to latest releases
  .gitignore
  dashboard/Chart.yaml
  dashboard/templates/dashboard-certs.yaml
  dashboard/templates/dashboard.yaml
  dashboard/templates/prometheus-configmap.yaml
  dashboard/values.yaml
  greymatter-secrets.yaml
  greymatter.yaml
  greymatter/requirements.yaml
  greymatter/values.yaml
  slo/Chart.yaml
  slo/templates/slo-certs.yaml
  slo/templates/slo.yaml
  slo/values.yaml
Labels: size/L

#352 345 mongo permission
  data/Chart.yaml
  data/templates/mongo.yaml
  greymatter/requirements.yaml
Labels: size/S

#385 Pin voyager port
  ci/scripts/show-voyager.sh
  docs/Deploy with Minikube.md
  edge/templates/edge-ingress.yaml
Labels: size/M

#384 remove cluster.local
  catalog/Chart.yaml
  catalog/templates/_helpers.tpl
  catalog/templates/bootstrap-zone-configmap.yaml
  control/Chart.yaml
  dashboard/Chart.yaml
  dashboard/templates/_helpers.tpl
  dashboard/values.yaml
  data/Chart.yaml
  data/templates/_helpers.tpl
  documentation/Chart.yaml
  documentation/templates/_helpers.tpl
  edge/Chart.yaml
  edge/templates/_helpers.tpl
  gm-control-api/Chart.yaml
  greymatter.yaml
  greymatter/Chart.yaml
  greymatter/requirements-dev.yaml
  greymatter/requirements.yaml
  jwt-gov/Chart.yaml
  jwt-gov/templates/_helpers.tpl
  jwt-gov/templates/jwt.yaml
  jwt-gov/values.yaml
  jwt/Chart.yaml
  jwt/templates/_helpers.tpl
  jwt/templates/jwt.yaml
  jwt/values.yaml
  slo/Chart.yaml
  slo/templates/_helpers.tpl
  slo/templates/slo.yaml
  spire/Chart.yaml
Labels: size/L

#380 enable mtls for control-api
  control/Chart.yaml
  control/templates/control-to-control-api-secret.yaml
  control/templates/control.yaml
  control/values.yaml
  gm-control-api/Chart.yaml
  gm-control-api/templates/gm-control-api-init.yaml
  gm-control-api/templates/gm-control-api-secret.yaml
  gm-control-api/templates/gm-control-api.yaml
  gm-control-api/values.yaml
  greymatter-secrets.yaml
  greymatter.yaml
  greymatter/requirements-dev.yaml
  greymatter/requirements.yaml
  greymatter/values.yaml
Labels: size/L
