Repository greymatter-io/helm-charts, pull requests merged in 2019-10, with the labels that each got.

#358 docs: using helm to generate k8s config
  README.md
  docs/Generating k8s Configs with Helm.md
Labels: size/M

#361 remove tests and update readme
  .gitignore
  gm-control-api/templates/tests/test-connection.yaml
  greymatter/README.md
  greymatter/templates/tests/catalog-test.yaml
  greymatter/templates/tests/documentation-test.yaml
Labels: size/L

#364 Update to make to set environment correctly.
  Makefile
Labels: size/XS

#369 bring credentials to greymatter-secrets so users know they exist
  greymatter-secrets.yaml
Labels: size/XL

#370 update the mongo credentials
  data/Chart.yaml
  data/templates/mongo-configmap.yaml
  data/templates/mongo-passwords.yaml
  data/values.yaml
  greymatter/requirements.yaml
Labels: size/S

#372 Voyager Minikube
  .gitignore
  Makefile
  ci/scripts/install-voyager.sh
  ci/scripts/voyager.patch
Labels: size/S
